export {default as Image} from "./Image/Image.tsx"
export {default as List} from "./List/List.tsx"
export {default as Point} from "./Point/Point.tsx"
export {default as Subtitle} from "./Subtitle/Subtitle.tsx"
export {default as Text} from "./Text/Text.tsx"