export {default as ErrorPage} from "./ErrorPage.tsx"
export {default as FaqPage} from "./FaqPage.tsx"
export {default as HomePage} from "./HomePage.tsx"
export {default as ProcessingPersonalDataPage} from "./ProcessingPersonalDataPage.tsx"
export {default as ThanksPage} from "./ThanksPage.tsx"
